# An example of ClusterConfig object using Managed Nodes
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Rameshroboshop
  region: us-east-1

managedNodeGroups:
  - name: Rameshmroboshop
    instanceTypes: ["m5.large","c3.large","c4.large","c5.large"]
    desiredCapacity: 3
    spot: true
    